{
	name: 'Authentic yoga',
	isIndex: true,
	specialty: 'Her kommer undertekst',
	background: 'Litt mer informasjon om Authentic Yoga og hva vi driver med',
	$main_image_type: 'image',
	main_image: '/remote/direct_uploads/1522340215_wallhalla-O80Q9e3IyK.jpg',
	$ingress_type: 'textarea',
	ingress: '',
	$practices_min: 1,
	practices_title: 'Rettninger',
	practices_beskrivelse: 'Beskrivelse kommer her',
	$hobby_background_type: 'image',
	hobby_background: 'https://s3-eu-west-1.amazonaws.com/enduro.mirror/direct_uploads/1485880478_pexels-photo-92323.jpeg',
	hobby_title: 'Priser',
	hobby_subtitle: 'Her finner du prisoversikt',
	cta_tagline: 'Kom i kontakt med Authentic yoga',
	cta_text: 'I am actively looking for new challenges',
	contact_email: 'contact@endurojs.com',
	page_title: 'Authentic yoga',
	display_edit_stamp: false,
	$style_expander: true,
	$style_info: 'won\'t work with the temp action',
	style: {
		$background_color_size: 'inline',
		$background_color_type: 'colorpicker',
		background_color: '#ffffff',
		$text_color_size: 'inline',
		$text_color_type: 'colorpicker',
		text_color: '#2b2928',
		$accent_color_size: 'inline',
		$accent_color_type: 'colorpicker',
		accent_color: '#fafdff'
	}
}